name: management-baseline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["infra/live/account-baseline/**", "infra/modules/**"]

permissions:
  contents: read
  id-token: write

jobs:
  deploy_workload_baseline:
    environment: CloudSec
    runs-on: ubuntu-latest

    strategy:
      matrix:
        account_id: ["435976456860"]

    defaults:
      run:
        working-directory: infra/live/account-baseline

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      
      - name: Show GitHub OIDC token claims
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN is set? $([ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] && echo yes || echo no)"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.MANAGEMENT_ACCOUNT_ID }}:role/github-org-bootstrap
          aws-region: us-east-1

      # If you're using central tfstate in Audit account, configure backend key per account:
      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}" \
            -backend-config="region=us-east-1" \
            -backend-config="key=account-baseline/${{ matrix.account_id }}/${{ matrix.account_id }}.tfstate"

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_github_org: tosicky
          TF_VAR_github_repo: cloud-security-guardrails
          TF_VAR_branch: main
          TF_VAR_management_account_id: ${{ vars.MANAGEMENT_ACCOUNT_ID }}
          TF_VAR_audit_account_id: ${{ vars.AUDIT_ACCOUNT_ID }}
          TF_VAR_workload_account_id: ${{ matrix.account_id }}
          TF_VAR_region: us-east-1
